#############################################################################
# Makefile for building: rope_intranet.app/Contents/MacOS/rope_intranet
# Generated by qmake (2.01a) (Qt 4.8.0) on: Fri Jun 15 10:40:47 2012
# Project:  rope_intranet.pro
# Template: app
# Command: /Users/tyeung/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake -spec ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile rope_intranet.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ -I.
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS)    
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/tyeung/QtSDK/Desktop/Qt/4.8.0/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp 
OBJECTS       = main.o
DIST          = ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf \
		rope_intranet.pro
QMAKE_TARGET  = rope_intranet
DESTDIR       = 
TARGET        = rope_intranet.app/Contents/MacOS/rope_intranet

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile rope_intranet.app/Contents/PkgInfo rope_intranet.app/Contents/Resources/empty.lproj rope_intranet.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) rope_intranet.app/Contents/MacOS/ || $(MKDIR) rope_intranet.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: rope_intranet.pro  ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++/qmake.conf ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf \
		../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile rope_intranet.pro
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/unix.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/mac.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/gcc-base-macx.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-base.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/common/g++-macx.conf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/qconfig.pri:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_functions.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/qt_config.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/exclusive_builds.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_pre.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_pre.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/dwarf2.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/debug.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/default_post.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/default_post.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/objective_c.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/declarative_debug.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/x86_64.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/warn_on.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/rez.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/mac/sdk.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/resources.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/uic.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/yacc.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/lex.prf:
../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++ CONFIG+=declarative_debug -o Makefile rope_intranet.pro

rope_intranet.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) rope_intranet.app/Contents || $(MKDIR) rope_intranet.app/Contents 
	@$(DEL_FILE) rope_intranet.app/Contents/PkgInfo
	@echo "APPL????" >rope_intranet.app/Contents/PkgInfo
rope_intranet.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) rope_intranet.app/Contents/Resources || $(MKDIR) rope_intranet.app/Contents/Resources 
	@touch rope_intranet.app/Contents/Resources/empty.lproj
	
rope_intranet.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) rope_intranet.app/Contents || $(MKDIR) rope_intranet.app/Contents 
	@$(DEL_FILE) rope_intranet.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,rope_intranet,g" -e "s,@TYPEINFO@,????,g" ../../../QtSDK/Desktop/Qt/4.8.0/gcc/mkspecs/macx-g++/Info.plist.app >rope_intranet.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/rope_intranet1.0.0 || $(MKDIR) .tmp/rope_intranet1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/rope_intranet1.0.0/ && (cd `dirname .tmp/rope_intranet1.0.0` && $(TAR) rope_intranet1.0.0.tar rope_intranet1.0.0 && $(COMPRESS) rope_intranet1.0.0.tar) && $(MOVE) `dirname .tmp/rope_intranet1.0.0`/rope_intranet1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/rope_intranet1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r rope_intranet.app
	-$(DEL_FILE) Makefile


check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

